name: service-template # 显式定义项目名称
services:
  # 1. 数据库服务 (MySQL)
  mysql:
    image: mysql:latest
    container_name: ${MYSQL_HOST}
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true  # 根密码
      MYSQL_DATABASE: ${MYSQL_DB}            # 自动创建的数据库名
      MYSQL_USER: ${MYSQL_USER}                   # 应用专用用户
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}        # 应用专用密码
    # ports:
    #   - "3306:3306"                         # 映射端口，方便本地 Navicat/DBeaver 连接
    volumes:
      - mysql_data:/var/lib/mysql              # 数据持久化

  # 2. 缓存服务 (Redis)
  redis:
    image: redis:latest
    container_name: ${REDIS_HOST}
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data                    # 数据持久化

  # 3. 应用服务 (FastAPI)
  app:
    build:
      context: .                            # 构建上下文：当前目录
      dockerfile: Dockerfile                # 指定 Dockerfile
    container_name: ${APP_NAME}
    restart: always
    # 这里的端口取决于你 Dockerfile 里 EXPOSE 的端口，通常是 8000
    ports:
      - "8521:8000"
    environment:
      ENVIRONMENT: production
    depends_on:
      mysql:
        condition: service_started          # 确保 db 启动后再启动 app
      redis:
        condition: service_started

volumes:
  mysql_data:
  redis_data:

