# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/


ARG PYTHON_VERSION=3.14
FROM python:${PYTHON_VERSION} as base


RUN pip install --upgrade pip && pip install --no-cache-dir poetry

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml ./

RUN poetry install --no-root

COPY . .

EXPOSE 8522

CMD poetry run fastmcp run main.py:mcp_web_app --transport=http --host=0.0.0.0 --port=8000
# 除了mcp_web_app，也可以指定mcp_echo_app或mcp_weather_app，前提是它们也要在main.py里定义或导被导入

